### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jbuil**

### CODE REVIEW

**Comment by fjlopez** [comment]
**Possible cause**: By default, GitHub Actions is disabled for your forked repository. Go to `https://github.com/UNIZAR-30246-WebEngineering/lab2-web-server/actions` and enable them,
and do a dummy pull request (e.g. add a whitespace character to the GUIDE.md)

**Comment by jbuil** [comment]
Done

**Comment by fjlopez** [comment]
Check your email inbox for an update to the lab send through Moodle. It is a fix to ensure that the badge shows that the CI has been triggered by a push request to the work branch.

**Review by fjlopez — CHANGES_REQUESTED** [review]

**Comment by jbuil** [comment]
Fixed

**Review by fjlopez — APPROVED** [review]

**Comment by fjlopez** [comment]
Merged!

**Pull request merged**
