### PR TITLE
No more static

### PR DESCRIPTION
**Pull request by rubenDTD**
There's an explanation [in my work branch](https://github.com/rubenDTD/lab2-web-server/blob/work/docs/no_more_static.md).

### CODE REVIEW

**Comment by fjlopez** [comment]
Your test is not working as you expect. Yes, it detects a 404 response, but is a 404 HTML page and not your 404 JSON message. The test should be fixed, and will fail because the handler is not working yet. How to fix this?

The best approach to remove the `ErrorController` is:

1. Add to `application.properties`:
   ```properties
   spring.mvc.throw-exception-if-no-handler-found=true
   ```
   It sets Spring to throw `NoHandlerFoundException` exception when no handler is found. 

2. Then, update your exception handler so it looks something similar to:
    ```kotlin
    @RestControllerAdvice
    class ExceptionControllerAdvice {
    @ExceptionHandler(NoHandlerFoundException::class)
      fun handleIllegalStateException(ex: NoHandlerFoundException): ResponseEntity<ErrorMessageModel> {
          val errorMessage = ErrorMessageModel(
              HttpStatus.NOT_FOUND.value(),
              ex.message
          )
          return ResponseEntity(errorMessage, HttpStatus.NOT_FOUND)
      }
    }   
    ```
3. But the above does not work unless you disable the default configuration of the `DefaultServlet` that searches files such as `error.html` to handle `NoHandlerFoundException` exceptions.
    ```kotlin
    @EnableWebMvc
    @Configuration
    class WebConfig :WebMvcConfigurer {
        override fun configureDefaultServletHandling(configurer: DefaultServletHandlerConfigurer) {
            // Do nothing instead of configurer.enable();
        }
     }   
     ```
4. Ensure that your test also checks that the body of the response is a JSON document equals to `{"status":404,"message":"No handler found for GET /randomURI"}`

Fix, it, update the docs and you will get the :gift:

**Comment by fjlopez** [comment]
@rubenDTD  any advances on this?

**Comment by rubenDTD** [comment]
@fjlopez  It's done! Allow me to update docs, I'll push it today.

**Comment by rubenDTD** [comment]
@fjlopez Push done!

**Comment by fjlopez** [comment]
Merged with :gift:

**Pull request merged**
