### PR TITLE
Changed README.md

### PR DESCRIPTION
**Pull request by motinsa**

### CODE REVIEW

**Comment by fjlopez** [comment]
## How to fix this problem

In local, in the branch `main`:

- Add to the file `.gitignore` a new line with `.idea`
- Remove the `.idea` folder from the git tree: `git rm --cached -r .idea`
- Commit this change
- Push this change to GitHub

The PR will be fine after this.

**Comment by fjlopez** [comment]
Check your email inbox for an update to the lab send through Moodle. It is a fix to ensure that the badge shows that the CI has been triggered by a push request to the work branch.

**Review by fjlopez — CHANGES_REQUESTED** [review]
Remember, only PR README.md from main (i.e. do the work in the work branch.)

**Review by fjlopez — APPROVED** [review]

**Comment by fjlopez** [comment]
@motinsa is the **test-it** implemented?

**Comment by motinsa** [comment]
Yes, it's a basic test which check the status of the two end-points. It's pushed on my work branch, the file is IntegrationTest.kt.

**Comment by fjlopez** [comment]
I will review it.

**Comment by fjlopez** [comment]
Surprisingly `skipSSL()` seems to be unnecessary in your code. My guess is that Spring Boot configures `org.apache.httpcomponents:httpclient` with the info in `application.properties`.

Anyway :gift: granted.

**Pull request merged**
