### PR TITLE
trigger github actions

### PR DESCRIPTION
**Pull request by 890464**

### CODE REVIEW

**Comment by fjlopez** [comment]
Well done but:
- copy the modified README.md from the work branch to the master branch.
- do the PR from there.
And that's it.

**Comment by 890464** [comment]
Professor, can you tell me how I should do this?!


   - copy the modified README.md from the work branch to the master branch.

**Comment by 890464** [comment]
porf i think now it is okey

**Comment by fjlopez** [comment]
Closed because #33 was accepted

**Pull request closed without merging**
