### PR TITLE
Practica 2 Oscar Palacin

### PR DESCRIPTION
**Pull request by 797021**

### CODE REVIEW

**Comment by fjlopez** [comment]
The work in https://github.com/797021/lab2-web-server/tree/work is incomplete. Please, push your local changes to the repo to verify that you have finished the lab.

**Comment by fjlopez** [comment]
Deteckt has detected the following issues:

```
src/main/kotlin/es/unizar/webeng/lab2/TimeComponent.kt:21:5: Unnecessary long whitespace [NoMultipleSpaces]
src/main/kotlin/es/unizar/webeng/lab2/TimeComponent.kt:10:1: Unexpected indentation (2) (should be 4) [Indentation]
src/main/kotlin/es/unizar/webeng/lab2/TimeComponent.kt:15:3: Unexpected indentation (2) (should be 4) [Indentation]
src/main/kotlin/es/unizar/webeng/lab2/TimeComponent.kt:22:5: Unexpected indentation (2) (should be 4) [Indentation]
src/main/kotlin/es/unizar/webeng/lab2/TimeComponent.kt:23:7: Unexpected indentation (2) (should be 4) [Indentation]
src/main/kotlin/es/unizar/webeng/lab2/TimeComponent.kt:14:20: Missing spacing before ":" [SpacingAroundColon]
src/main/kotlin/es/unizar/webeng/lab2/TimeComponent.kt:1:1: Trailing space(s) [NoTrailingSpaces]
```

Running locally `./gradlew build` may fix these issues. Otherwise, you can find and fix these style issues before pushing your changes to GitHub.

**Comment by 797021** [comment]
I corrected the mistake

**Comment by fjlopez** [comment]
Merged!

**Pull request merged**
