### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GueorguiKachan**

### CODE REVIEW

**Comment by fjlopez** [comment]
Your workflow seems to be disabled. Can you run it manually?

**Comment by fjlopez** [comment]
**Possible cause**: By default, GitHub Actions is disabled for your forked repository. Go to `https://github.com/GueorguiKachan/lab2-web-server/actions` and enable them,
and do a dummy pull request (e.g. add a whitespace character to the GUIDE.md)

**Comment by GueorguiKachan** [comment]
Github Actions enabled and dummy commit done

**Comment by fjlopez** [comment]
Check your email inbox for an update to the lab send through Moodle. It is a fix to ensure that the badge shows that the CI has been triggered by a push request to the work branch.

**Comment by GueorguiKachan** [comment]
CI.yml changed, Build Status updated, now the badge is green.

**Comment by fjlopez** [comment]
Hum, something that you should fix first is the location of your `application.properties`. It must be in the `src/main/resources' folder, not in `src/main/resources/templates`.

**Comment by fjlopez** [comment]
Merged!

**Pull request merged**
